name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, shopdesk]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Deploy only if CI passed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into server and deploy
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_IP: ${{ secrets.SSH_IP }}
          REPO_URL: ${{ secrets.REPO_URL }}
          CURRENT_VERSION: "main"  # Change this if you want to deploy a specific version
          ROLLBACK_VERSION: "version1.3"  # Last stable version
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_IP" "
            cd shopdesk-fe || { git clone $REPO_URL shopdesk-fe && cd shopdesk-fe; }
            git checkout $CURRENT_VERSION
            git pull origin $CURRENT_VERSION || { echo 'Git pull failed'; exit 1; }
            
            pm2 delete shopdesk || true
            echo '$SSH_PASSWORD' | sudo -S fuser -k 7777/tcp || echo 'No process found on port 7777'
            
            if bun install && bun run build; then
              pm2 start \"bun run start\" --name \"shopdesk\" --watch
              pm2 save
              echo 'Deployment successful'
            else
              echo 'Deployment failed! Rolling back...'
              git checkout $ROLLBACK_VERSION
              git pull origin $ROLLBACK_VERSION
              bun install && bun run build
              pm2 start \"bun run start\" --name \"shopdesk\" --watch
              pm2 save
            fi
          "